[phases.setup]
nixPkgs = ["nodejs_23"]

[phases.build]
cmds = [
  "find node_modules -mindepth 1 -maxdepth 1 ! -name '.cache' -exec rm -rf {} + || true",
  "rm -f package-lock.json",
  "npm install --force",
  "npm run build"
]

[start]
cmd = "npm start"
